# Generated by Django 4.1.7 on 2023-05-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_product_count_remove_order_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма заказа'),
        ),
    ]
