# Generated by Django 4.1.7 on 2023-05-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_sum',
            new_name='total_price',
        ),
    ]
