# Generated by Django 4.1.7 on 2023-05-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма бонуса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='Сумма заказа'),
        ),
    ]
