# Generated by Django 4.1.7 on 2023-05-06 14:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(blank=True, choices=[('Электроника', 'Electronics'), ('Clothing', 'Clothing'), ('Красота и здоровье', 'Beauty'), ('Дом и интерьер', 'Home'), ('Спорт товары', 'Sports'), ('Игрушки и игры', 'Toys'), ('Книги', 'Books'), ('Товары для животных', 'Animalproducts')], max_length=100, null=True, verbose_name='Категория')),
                ('product_image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Изображение товара')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Количество обзоров')),
                ('sale', models.FloatField(blank=True, null=True, verbose_name='Процент скидки')),
                ('product_count', models.IntegerField(verbose_name='Количество товаров')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв о товаре',
                'verbose_name_plural': 'Отзывы о товаре',
                'ordering': ('-created_at',),
            },
        ),
    ]
