# Generated by Django 4.1.7 on 2023-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_options_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products_images/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
